# Generated by Django 3.0 on 2021-01-27 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblparentmaster',
            name='parentAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblparentmaster',
            name='parentCity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tblparentmaster',
            name='parentZIP',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblparentmaster',
            name='stateID',
            field=models.ForeignKey(default='IL', on_delete=django.db.models.deletion.CASCADE, to='app.TblStateMaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblparentmaster',
            name='parentFullName',
            field=models.CharField(blank=True, db_column='parentFullName', max_length=255, null=True),
        ),
    ]
