# Generated by Django 3.0 on 2021-01-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210127_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblstatemaster',
            options={'ordering': ['stateID']},
        ),
        migrations.AddField(
            model_name='tblissuemaster',
            name='issueLongDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
