# Generated by Django 3.0 on 2021-01-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210129_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblissuemaster',
            name='issueSRGID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblissuemaster',
            name='issueLongDescription',
            field=models.TextField(blank=True, db_column='issueLongDescription', null=True),
        ),
    ]
