# Generated by Django 4.2.7 on 2023-12-05 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_tblappealmaster_appealstructure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tblappealmaster",
            name="appealStructure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CIRP", "CIRP"),
                    ("Optional", "Optional"),
                    ("Individual", "Individual"),
                ],
                db_column="appealStructure",
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tblprovidermaster",
            name="provMasterDeterminationType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FR", "FR"),
                    ("Other", "Other"),
                    ("RNPR", "RNPR"),
                    ("NPR", "NPR"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TblHospContactMaster",
            fields=[
                ("hospContactID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "hospContactFirstName",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "hospContactLastName",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "hospContactTitle",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "hospContactEmail",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "parentID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.tblparentmaster",
                    ),
                ),
            ],
        ),
    ]
