# Generated by Django 3.0 on 2021-02-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210129_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblappealmaster',
            options={},
        ),
    ]
