# Generated by Django 3.0 on 2021-02-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210204_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblappealmaster',
            name='fiID',
            field=models.ForeignKey(blank=True, db_column='fiID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblFIMaster'),
        ),
        migrations.AddField(
            model_name='tblappealmaster',
            name='prrbContactID',
            field=models.ForeignKey(blank=True, db_column='prrbContactID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblPRRBContactMaster'),
        ),
        migrations.AddField(
            model_name='tblappealmaster',
            name='staffID',
            field=models.ForeignKey(blank=True, db_column='staffID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblStaffMaster'),
        ),
        migrations.AddField(
            model_name='tblappealmaster',
            name='statusID',
            field=models.ForeignKey(blank=True, db_column='statusID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblStatusMaster'),
        ),
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealName',
            field=models.CharField(blank=True, db_column='appealName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Optional', 'Optional'), ('CIRP', 'CIRP')], db_column='appealStructure', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblprovidermaster',
            name='provMasterAmount',
            field=models.IntegerField(blank=True, db_column='provMasterAmount', null=True),
        ),
    ]
