# Generated by Django 3.0 on 2021-02-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210205_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblprovidermaster',
            old_name='provMasterAmount',
            new_name='provMasterImpact',
        ),
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Optional', 'Optional'), ('CIRP', 'CIRP')], db_column='appealStructure', max_length=25, null=True),
        ),
    ]
