# Generated by Django 3.0 on 2021-02-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210205_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('Optional', 'Optional'), ('Individual', 'Individual'), ('CIRP', 'CIRP')], db_column='appealStructure', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblprovidermaster',
            name='provMasterImpact',
            field=models.DecimalField(blank=True, db_column='provMasterAmount', decimal_places=0, max_digits=19, null=True),
        ),
    ]
