# Generated by Django 3.0 on 2021-02-05 17:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210205_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblActionMaster',
            fields=[
                ('actionID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('lead_time', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriticalDatesMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dueDate', models.DateField()),
                ('response', models.TextField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20, null=True)),
                ('actionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblActionMaster')),
                ('caseNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TblAppealMaster')),
            ],
        ),
    ]
