# Generated by Django 3.0 on 2021-02-05 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_criticaldatesmaster_tblactionmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticaldatesmaster',
            name='caseNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblAppealMaster'),
        ),
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('Optional', 'Optional'), ('CIRP', 'CIRP'), ('Individual', 'Individual')], db_column='appealStructure', max_length=25, null=True),
        ),
    ]
