# Generated by Django 3.0 on 2021-02-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210205_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblactionmaster',
            name='id',
        ),
        migrations.AlterField(
            model_name='tblactionmaster',
            name='actionID',
            field=models.CharField(default='', max_length=25, primary_key=True, serialize=False),
        ),
    ]
