# Generated by Django 3.0 on 2021-03-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210205_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcasedeterminationmaster',
            name='providerNumber',
            field=models.ForeignKey(blank=True, db_column='providerID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblProviderNameMaster'),
        ),
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('Optional', 'Optional'), ('Individual', 'Individual'), ('CIRP', 'CIRP')], db_column='appealStructure', max_length=25, null=True),
        ),
    ]
