# Generated by Django 3.0 on 2021-03-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210310_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblprovidermaster',
            name='provMasterFiscalYear',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('CIRP', 'CIRP'), ('Individual', 'Individual'), ('Optional', 'Optional')], db_column='appealStructure', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblprovidermaster',
            name='provMasterDeterminationType',
            field=models.CharField(blank=True, choices=[('RNPR', 'RNPR'), ('NPR', 'NPR'), ('FR', 'FR')], max_length=4, null=True),
        ),
    ]
