# Generated by Django 3.0 on 2021-03-25 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210323_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('CIRP', 'CIRP'), ('Optional', 'Optional')], db_column='appealStructure', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblprovidermaster',
            name='provMasterDeterminationType',
            field=models.CharField(blank=True, choices=[('FR', 'FR'), ('RNPR', 'RNPR'), ('NPR', 'NPR')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='NPRDueDatesMaster',
            fields=[
                ('nprID', models.AutoField(db_column='provMasterID', primary_key=True, serialize=False)),
                ('nprFY', models.IntegerField()),
                ('nprDate', models.DateField()),
                ('parentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblParentMaster')),
                ('providerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblProviderNameMaster')),
            ],
        ),
    ]
