# Generated by Django 3.0 on 2021-03-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210325_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nprduedatesmaster',
            name='parentID',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblParentMaster'),
        ),
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('Optional', 'Optional'), ('Individual', 'Individual'), ('CIRP', 'CIRP')], db_column='appealStructure', max_length=25, null=True),
        ),
    ]
