# Generated by Django 3.0 on 2021-04-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210405_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticaldatesmaster',
            options={'ordering': ['dueDate']},
        ),
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('CIRP', 'CIRP'), ('Optional', 'Optional')], db_column='appealStructure', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblprovidermaster',
            name='provMasterDeterminationType',
            field=models.CharField(blank=True, choices=[('NPR', 'NPR'), ('FR', 'FR'), ('RNPR', 'RNPR')], max_length=4, null=True),
        ),
    ]
