# Generated by Django 3.0 on 2021-04-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210406_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('CIRP', 'CIRP'), ('Individual', 'Individual'), ('Optional', 'Optional')], db_column='appealStructure', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblprovidernamemaster',
            name='providerIsClient',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
