# Generated by Django 3.0 on 2021-04-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210412_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticaldatesmaster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblprovidermaster',
            name='provMasterDeterminationType',
            field=models.CharField(blank=True, choices=[('RNPR', 'RNPR'), ('FR', 'FR'), ('NPR', 'NPR')], max_length=4, null=True),
        ),
    ]
