# Generated by Django 3.0 on 2021-04-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210412_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticaldatesmaster',
            old_name='id',
            new_name='dateID',
        ),
        migrations.AlterField(
            model_name='tblprovidermaster',
            name='provMasterDeterminationType',
            field=models.CharField(blank=True, choices=[('NPR', 'NPR'), ('RNPR', 'RNPR'), ('FR', 'FR')], max_length=4, null=True),
        ),
    ]
