# Generated by Django 3.0 on 2021-04-12 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210412_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalDatesMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dueDate', models.DateField()),
                ('response', models.TextField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Not Applicable', 'Not Applicable'), ('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20, null=True)),
                ('actionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblActionMaster')),
            ],
            options={
                'ordering': ['dueDate'],
            },
        ),
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('Optional', 'Optional'), ('Individual', 'Individual'), ('CIRP', 'CIRP')], db_column='appealStructure', max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='TblCriticalDatesMaster',
        ),
        migrations.AddField(
            model_name='criticaldatesmaster',
            name='caseNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TblAppealMaster'),
        ),
    ]
