# Generated by Django 3.0 on 2021-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210412_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblappealmaster',
            name='appealStructure',
            field=models.CharField(blank=True, choices=[('CIRP', 'CIRP'), ('Optional', 'Optional'), ('Individual', 'Individual')], db_column='appealStructure', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tblprovidermaster',
            name='provMasterDeterminationType',
            field=models.CharField(blank=True, choices=[('RNPR', 'RNPR'), ('NPR', 'NPR'), ('FR', 'FR')], max_length=4, null=True),
        ),
    ]
